name: RegisterLogin
main: RegisterLogin\KienMC\Main
api: 5.0.0
version: 0.0.1
author:
- Kiên MC
description: Plugin Register And Login For Pocketmine MP 5
permissions:
   register.cmd:
      default: true
   login.cmd:
      default: true
   checkpass.cmd:
      default: op
